version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=${PORT}
      - PUB_SUB_FILE_PATH=${PUB_SUB_FILE_PATH}
      - PUB_SUB_TOPIC=${PUB_SUB_TOPIC}
    volumes:
      - ./host_files:/app/data
      - app_data:/app/persistent_data

volumes:
  app_data:
    driver: local
